### ISSUE TITLE
XRoad Installation with EJbca Server and SignServer?

### ISSUE THREAD

**Issue by darapenhchet** [nordic-institute/X-Road-development#13]
Dear XRoad,

May I ask you how to install the XRoad and using the Ejbca Server (CA, OCSP) and SignServer (TSA)?

Could you share me any resources about it?

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi,

EJBCA and SignServer are external components and not part of X-Road software. Therefore, we do not provide support for installing and/or running them.

However, we provide a Test-CA with OCSP and TSA that can be used in test and development environments. More information can be found [here](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md).

Test-CA with OCSP and TSA can be installed manually or using [Ansible](https://github.com/nordic-institute/X-Road/tree/develop/ansible).

Regards,
Petteri

**Comment by darapenhchet** [comment]
Dear Petteri Kivimäki,

May I ask you some questions. I am using the TSA Test Sample and I cannot
register the client in the security server. Why the TSA is not working?
[image: image.png]

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Why I cannot register new client in the Security Server? Why the TSA is not working well?
![image](https://user-images.githubusercontent.com/8038324/62507591-28438c80-b82f-11e9-9f00-003dcfee5bfe.png)

Best Regards,
Dara Penhchet

**Comment by petkivim** [comment]
Hi Dara,

Have you completed the steps described below?

1. Configure the TSA on the Central Server according to the [instructions](https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-1.4Addingtime-stampingservice)?

2. Configure the TSA on the Security Server according to the [instructions](https://confluence.niis.org/pages/viewpage.action?pageId=6783483#HowtoConfigureCentralServer?-3.3Configuringthetime-stampingservice)?

If you have completed both steps and TSA is still not working, please check the log file `/var/log/xroad/proxy.log` for additional information about the problem.

Best regards,
Petteri

**Comment by darapenhchet** [comment]
Could you tell the solution for Time Stamp Authority? what should we use such as SignServer or anything else?

And how about the Certificate Authority should we use the Ejbca or Window Server Certificate Authority?

**Comment by petkivim** [comment]
> Could you tell the solution for Time Stamp Authority? what should we use such as SignServer or anything else?

The [Test-CA with OCSP and TSA](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md) can be used in test and development environment. Alternatively, you could use PrimeKey's TSA solution. You can also use any commercial TSA service that implements [Internet X.509 Public Key Infrastructure Time-Stamp Protocol (TSP)](https://www.ietf.org/rfc/rfc3161.txt).

> And how about the Certificate Authority should we use the Ejbca or Window Server Certificate Authority?

The [Test-CA with OCSP and TSA](https://github.com/nordic-institute/X-Road/blob/develop/ansible/TESTCA.md) can be used in test and development environment. Alternatively, you can use EJBCA or some commercial Certificate Authority that is able to process certificate signing requests conforming to PKCS10. In addition, the CA must distribute certificate validity information via the [OCSP protocol](https://tools.ietf.org/html/rfc6960).

**Comment by darapenhchet** [comment]
Thanks you
