### ISSUE TITLE
adding 3rd security server in the Ubuntu X-Road

### ISSUE THREAD

**Issue by bmalila** [nordic-institute/X-Road-development#14]
Hi,
Hi can you please confirm if I can install more than 2 security servers on the virtual X-Road instance. I have successfully install two, but failing to install the third one. I get the following error message:
[ok: demos1]                                                                                                                                                  fatal: [demo-ss3]: FAILED! => {"changed": false, "msg": "No package matching 'xroad-securityserver' is available"}
ok: [demo-ss2]

**Comment by petkivim** [comment]
Hi @bmalila 

Yes, it is possible to install more than 2 Security Servers using the [Ansible script](https://github.com/nordic-institute/X-Road/tree/develop/ansible). It's enough to add new Security Servers in the `[ss-servers]` of the [hosts](https://github.com/nordic-institute/X-Road/blob/develop/ansible/hosts/lxd_hosts.txt#L14) file. 

```
[ss-servers]
xroad-lxd-ss1 ansible_connection=lxd
xroad-lxd-ss2 ansible_connection=lxd
xroad-lxd-ss3 ansible_connection=lxd
```

Best regards,
Petteri

**Comment by bmalila** [comment]
Thanks for the confirmation. We will keep trying.Kind regards,Bessie.
    On ‎Monday‎, ‎21‎ ‎October‎ ‎2019‎ ‎08‎:‎48‎:‎02‎ ‎SAST, Petteri Kivimäki <notifications@github.com> wrote:  
 
 
Hi @bmalila

Yes, it is possible to install more than 2 Security Servers using the Ansible script. It's enough to add new Security Servers in the [ss-servers] of the hosts file.
[ss-servers]
xroad-lxd-ss1 ansible_connection=lxd
xroad-lxd-ss2 ansible_connection=lxd
xroad-lxd-ss3 ansible_connection=lxd

Best regards,
Petteri
