### ISSUE TITLE
CSR Structure issue on Security Server

### ISSUE THREAD

**Issue by figueroarv** [nordic-institute/X-Road-development#22]
Hi there!

On develop branch (7.0.0), the Auth and Sign CSR generated from Security Server have a different structure that CSR generated from for example Security Server version 6.24.1.

As you can see bleow, in develop version, field SN isn't present and the order of the other fields is not the same.
In the next scenario, xroadcentral is the Central Server based on develop version 7.0:

Can this be an issue regarding just to the develop enviroment or can be related to a misconfiguration during SS install?

**Auth CSR from X-Road 6.24.1**
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: **SN**=1234567, **CN**=Some Common Name

Auth CSR from X-Road develop
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: **C**=AR, **O**=xroadcentral, **CN**=xroadcentral/GOB/GOB0000002/SECURITYSERVER_HOSTNAME

**Sign CSR from X-Road 6.24.1**
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: **SN**=1234567, **CN**=Some Common Name

Sign CSR from X-Road develop
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: **C**=AR, **O**=xroadcentral, **OU**=GOB, **CN**=GOB0000002/serialNumber=xroadcentral/GOB/GOB0000002/SECURITYSERVER_HOSTNAME

Regards,

**Comment by petkivim** [comment]
Hi @figueroarv 

The values in the CSRs depend on the certificate profile that's defined for the Certificate Authority on the [Central Server](https://confluence.niis.org/pages/viewpage.action?pageId=6783483&preview=/6783483/6783500/certificate-profile-info.png#HowtoConfigureCentralServer?-1.3Addingcertificationservice). Also, if you have multiple CAs defined on the Central Server, they may all use different certificate profiles. Based on your example it seems that the CSRs from version 6.24.1 and from `develop` branch have been generated using two different certificate profiles. In the code base there shouldn't be any changes that cause the difference.

Best regards,
Petteri

**Comment by figueroarv** [comment]
Hi @petkivim 

Thanks so much for reply! Great, we have included on the source code  (7.0) the java class of our certificate profile info (ARAuthCertificateProfileInfo.java) to add support to our country code (C=AR).

According to your comments, we must to review that java class, fix it and rebuild; may be to check what profile info we are using on 6.2.4 will give us some advice.

Thank you!

**Comment by petkivim** [comment]
Hi @figueroarv 

It's possible to include a certificate profile in a single Java class, but it's a common practice to split the code in four different classes. More information can be found from [this](https://confluence.niis.org/pages/viewpage.action?pageId=4293076) Knowledge Base article. Since you only have one class in your profile, it's better to double check that it contains all the required elements.

Best regards,
Petteri

**Comment by figueroarv** [comment]
Hi @petkivim,

Yes, we have splited the code in that four classes; clearly, now we need to align these profiles with the CA Policies.

Thank you again!

Regards,

**Comment by figueroarv** [comment]
Need to define certificate profiles based on CA Certification Policies.
