### ISSUE TITLE
Sign-up on jira.niis.org doesn't work

### ISSUE THREAD

**Issue by CharlesYeh** [nordic-institute/X-Road-development#4]
I get a generic error on https://jira.niis.org/secure/Signup.jspa after submission:
> You can't sign up right now
> An error occurred while trying to set up your user account. You could let the administrator know you can't sign up right now or try again later.

**Comment by petkivim** [comment]
Probably your password did not meet the complexity requirements. The password must contain at least 1 lower case letter, 1 upper case letter, 1 digit, 1 special character. The length must be at least 10 characters. Please try again using a password that meets the requirements.

**Comment by CharlesYeh** [comment]
Thanks, that worked.
