### ISSUE TITLE
Cannot start SS services

### ISSUE THREAD

**Issue by hainguyen291** [nordic-institute/X-Road-development#5]
Hi everyone, 

I just installed new SS. However, I couldn't start SS services as image below

![image](https://user-images.githubusercontent.com/12641471/43948597-6cd67330-9cb5-11e8-81a2-d055859ef046.png)

Please let me know what I should do.

Thanks,

Hai

**Comment by petkivim** [comment]
Hi @hainguyen291,

What does `$ java -version` command return? Your `JAVA_HOME` points to Java 7, but X-Road requires Java 8.

Regards,
Petteri

**Comment by hainguyen291** [comment]
You are right. I don't notice about that. I will install java 8 now.

Thanks,

Hai

**Comment by hainguyen291** [comment]
BTW, is java 11 OK?
![image](https://user-images.githubusercontent.com/12641471/43952607-9f12813a-9cc0-11e8-9e48-d48c18f49279.png)

**Comment by hainguyen291** [comment]
I tried java 11 but the problem still be remained. I think I should use java 8 instead, don't I?

Thanks

**Comment by petkivim** [comment]
Unfortunately, Java 11 is not OK either - X-Road requires Java 8. You should remove Java 11 and install Java 8 (`sudo apt install openjdk-8-jre-headless`).

**Comment by hainguyen291** [comment]
Thanks @petkivim . I solved my problem after install java 8 already!

Thank you so much.

Hai.
