### ISSUE TITLE
Cannot register subsystem

### ISSUE THREAD

**Issue by hainguyen291** [nordic-institute/X-Road-development#6]
Hi everyone,

I tried to add new client on SS today, but it was not successful.

![image](https://user-images.githubusercontent.com/12641471/44771587-9995ac80-ab95-11e8-828f-8a8369c04d47.png)

It seems that I need to implement clientReg/clientDeletion on management service, don't I? 

Best regards,
Hai

**Comment by petkivim** [comment]
Hi,

You have not configured the management service provider on Central Server yet:

https://github.com/nordic-institute/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#42-configuring-the-management-service-provider

Regards,
Petteri

**Comment by hainguyen291** [comment]
Hi petkivim,

You are right, I forgot to configured the management service provider.

Thank you so much,
Hai
