### ISSUE TITLE
Where the CA certificate file is located in?

### ISSUE THREAD

**Issue by yamato-k** [nordic-institute/X-Road-development#9]
Hello @petkivim,

I'm trying to configure the certification services and the timestamping services flowing [11. Managing the Approved Certification Services](https://github.com/yamato-k/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#11-managing-the-approved-certification-services).

But I'm not sure how to flow this instruction,` 2. Locate the certification service CA certificate file and click Next` on [11.1 Adding an Approved Certification Service](https://github.com/yamato-k/X-Road/blob/develop/doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md#111-adding-an-approved-certification-service).

Where the CA certificate file is located in?

![image](https://user-images.githubusercontent.com/34284486/46913074-3f27a280-cfc1-11e8-87ea-5156d0d30d3f.png)

Probably, I initialized a new test-CA server automatically with Ansible, according to instructions in [ansible/README.md](https://github.com/yamato-k/X-Road/blob/develop/ansible/README.md) and [Test-CA with TSA and OCSP](https://github.com/yamato-k/X-Road/blob/develop/ansible/README.md)

Best Regards,

Yamato

P/S: My OS: Ubuntu 16.04.5 LTS

**Comment by petkivim** [comment]
Hi @yamato-k 

CA certificate, OCSP certificate and TSA certificate are all located in `/home/ca/CA/certs` directory on the host where test-CA is running. By default, test-CA is installed on the same host with the Central Server. If you're using LXD containers, then test-CA is running inside of `xroad-lxd-cs` container and you must log in to the container (`lxc exec xroad-lxd-cs bash`) to be able to copy the certificates from the LXD container to your workstation. Once you have saved the certificates on you workstation, you're able to complete this step `2. Locate the certification service CA certificate file and click Next`.

**Comment by yamato-k** [comment]
I got it.

Thank you for always giving me much detailed information.
